Implements the SingleSelect mode
scireum/token-autocomplete pull request #18
Opened 2021-05-05 06:44 UTC by meg1502

Fixes: SIRI-322

2021-05-05 07:02 UTC, sabieber requested changes

2021-05-05 07:02 UTC, sabieber commented on lib/token-autocomplete.ts
> +        }
```suggestion
            me.parent.textInput.contentEditable = 'true';
        }
```

2021-05-05 07:02 UTC, sabieber commented on lib/token-autocomplete.ts
> +                this.parent.autocomplete.suggestions.firstChild.dispatchEvent(new MouseEvent('click'));
Frage: Kennt der IE11 die Klasse MouseEvent?

2021-05-05 07:02 UTC, sabieber commented on lib/token-autocomplete.ts
> +            let singleSelect = me.select as SingleSelect;
s.o.

2021-05-05 09:26 UTC, meg1502 commented on lib/token-autocomplete.ts
> +                this.parent.autocomplete.suggestions.firstChild.dispatchEvent(new MouseEvent('click'));
Ne bei KeyboardEvent auch nicht. Ich würde das später nochmal gesondert fixen, hab jetzt auf die schnelle nicht nen mega tollen polyfill gefunden und die alte api ist auch sehr doof zu benutzen

2021-05-05 09:33 UTC, sabieber commented on lib/token-autocomplete.ts
> +                this.parent.autocomplete.suggestions.firstChild.dispatchEvent(new MouseEvent('click'));
Alles klar

2021-05-05 09:34 UTC, sabieber approved these changes

2021-05-07 07:51 UTC, idlira requested changes

2021-05-07 07:51 UTC, idlira commented on built/token-autocomplete.js
> +            this.select = new TokenAutocomplete.SinlgeSelect(this);
typo

2021-05-07 07:51 UTC, idlira commented on built/token-autocomplete.js
> +    TokenAutocomplete.SinlgeSelect = /** @class */ (function () {
rename typo

2021-05-07 08:21 UTC, qw3ry approved these changes

2021-05-07 08:21 UTC, qw3ry commented on built/token-autocomplete.js
> +        else if (this.options.selectMode == SelectModes.SINGLE) {
formatting

2021-05-07 08:22 UTC, ymo-sci commented on lib/token-autocomplete.ts
> +    static SinlgeSelect = class implements SingleSelect {
```suggestion
    static SingleSelect = class implements SingleSelect {
```

2021-05-07 08:22 UTC, ymo-sci commented on lib/token-autocomplete.ts
> +            this.select = new TokenAutocomplete.SinlgeSelect(this);
```suggestion
            this.select = new TokenAutocomplete.SingleSelect(this);
```

2021-05-07 08:22 UTC, qw3ry commented on built/token-autocomplete.js
> +        else if (this.options.selectMode == SelectModes.SINGLE) {
ah die Datei ist generiert? dann nvm

2021-05-07 11:50 UTC, idlira approved these changes

2021-05-07 11:51 UTC, sabieber approved these changes

2021-05-07 12:26 UTC, cschierle approved these changes

2021-05-07 12:27 UTC, merged